### ISSUE TITLE
Device registration

### ISSUE THREAD

**Issue by tgpmoraes** [meccano-iot/raspberry-pi-library#5]
Hi,
I have just installed the all three layers: gateway, service manager and web console. I couldn't be able to start service manager because I don't have AWS account. Anyway, I go ahead, and I tried to registrer a device (raspberry pi), but when I execute the example.py, I am recieving the following error:

Meccano IoT
(c) 2015-2016 - Magazine Luiza
                Luizalabs

Device Id: b8:27:eb:02:08:22
Configuring server...
Starting Registration...
Device Group   : teste
Security Token : eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkZXZpY2UiOiJiODoyNzplYjowMjowODoyMiIsImlhdCI6MTQ2MDQ3NDA0OH0.IP3KrJa6aWgaO78Kz_UfJwoMW9YrCIRNY0xL3dlhn_I
Getting time from server...
Could not get time from server...
Could not connect to Meccano Network

Is it any port that I need to open?
Regards,
Tiago Moraes

**Comment by diegofernandes** [comment]
@tgpmoraes the Gateway just use one port, Apparently the gateway is accessible, but you could try a manual request.
Try to run this follow command e send us the result.
```
curl -X GET -H "Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkZXZpY2UiOiJiODoyNzplYjowMjowODoyMiIsImlhdCI6MTQ2MDQ3NDA0OH0.IP3KrJa6aWgaO78Kz_UfJwoMW9YrCIRNY0xL3dlhn_I" http://<host>:<port>/api/gateway/b8:27:eb:02:08:22
```

Tks

**Comment by rogeriobiondi** [comment]
@tgpmoraes, have you authorized your device in web console? If not, take a look at the webconsole. The device should appear as WAITING_APPROVE and after approval it will receive the token, de device group and communicate with the network properly.

Best regards,
Rogerio

**Comment by tgpmoraes** [comment]
Hi Diego,

Following your suggestion, I executed the command, and I got no results in the raspberry, but in the gateway I got:
Meccano IoT Gateway listening on 8080, in test mode
GET /api/gateway/b8:27:eb:02:08:22 406 19.220 ms - -

Rodrigo and Diego,

About the webconsole, I have had authorized, but there is a message - "Device waiting to connect the meccano network", and the has unknow as status.

Regards,
Tiago Moraes

**Comment by diegofernandes** [comment]
@tgpmoraes could you send us the result of the curl command?

**Comment by tgpmoraes** [comment]
There is no results:

pi@raspberrypi /app/raspberry-pi-library $ curl -X GET -H "Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkZXZpY2UiOiJiODoyNzplYjowMjowODoyMiIsImlhdCI6MTQ2MDQ3NDA0OH0.IP3KrJa6aWgaO78Kz_UfJwoMW9YrCIRNY0xL3dlhn_I" http://gateway.eastus2.cloudapp.azure.com:8080/api/gateway/b8:27:eb:02:08:22
pi@raspberrypi /app/raspberry-pi-library $

**Comment by tgpmoraes** [comment]
Now it worked. Thanks Diego
